### ISSUE TITLE
Set up Markdown preprocessor React blog project

### ISSUE THREAD

**Issue by immanuelqrw** [immanuelqrw/Seshat#1]
### Description
Find and select a Markdown processor style framework like Jekyll or Gatsby and set it up to connect to a custom domain like blog.immanuelqrw.dev

### Details
Need a blog for posterity and interesting thoughts

### Acceptance Criteria
- Blog accessible through custom domain with a Lorem Ipsum article

### Tasks
- [x] Find and choose Markdown processor framework
- [x] Build to be accessible through github pages
- [x] Connect to custom domain `blog.immanuelqrw.dev`
- [x] Add Lorem Ipsum article
